name = "CryptoCurrencies"
uuid = "8b232f04-5eca-11e9-25cd-cfbcb1f62064"
authors = ["Simon Castano <simon@brane.cc>"]
version = "0.0.1"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
